src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 200)]
    private ?string $content = null;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;


use App\Form\PictureProfilType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/profil', name: 'profile_')]

final class ProfileController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(): Response
    {


        return $this->render('profile/index.html.twig', [
            'controller_name' => 'Profil de l\'utilisateur',
        ]);
    }

    #[Route('/posts', name: 'posts')]
    public function posts(): Response
    {
        /** @var \App\Entity\User $user */
        $user = $this->getUser();
        $posts = $user->getPosts();
        return $this->render('profile/posts.html.twig', [
            'posts' => $posts,
        ]);
    }
    #[Route('/modifier', name: 'modifier')]
    public function uploadPicture(
        Request $request,
        SluggerInterface $slugger,
        #[Autowire('%kernel.project_dir%/public/uploads')] string $picturesDirectory,
        EntityManagerInterface $entityManager
    ): Response {
        $user = $this->getUser();
        $form = $this->createForm(PictureProfilType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $pictureFile */
            $pictureFile = $form->get('picture')->getData();

            if ($pictureFile) {
                  /** @var \App\Entity\User $user */
                $originalFilename = pathinfo($pictureFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);

                $newFilename = $safeFilename . '-' . uniqid() . '.' . $pictureFile->guessExtension();

                try {
                    $pictureFile->move($picturesDirectory, $newFilename);
                } catch (FileException $e) {
                    echo "Image non valide " . $e->getMessage();
                }
                $user->setPhoto($newFilename);
            }
            $entityManager->persist($user);
            $entityManager->flush();


            return $this->redirectToRoute('profile_index');
        }
        return $this->render('profile/modifier.html.twig', [
            'pictureProfil' => $form->createView(),
            'user' => $user,
        ]);
    }
}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Profil Utilisateur
{% endblock %}

{% block body %}
	<a href="{{ path('app_home_page') }}">Page d'accueil</a>
	<div class="container text-center">
		<div>
			<div class="col" _msttexthash="77766" _msthash="252">
				<h1>Hello
					{{ controller_name }}!</h1>
				{% if app.user.photo %}
					<img src="{{ asset('uploads/' ~ app.user.photo) }}" alt="Photo de profil">
				{% else %}
					<p>Aucune photo de profil.</p>
				{% endif %}
				Username :
				{{ app.user.username }}
			</div>
		</div>
		<div class="row">
			<div>
				<p>écrire ici sa bio</p>
			</div>

			<div class="col" _msttexthash="52403" _msthash="256">
				<a href="{{ path('profile_modifier') }}" class="btn-primary">Modifier le profil</a>
			</div>
		</div>
	</div>
	<div class="col">
		<a href="{{ path('profile_posts') }}">Posts</a>
	</div>

{% endblock %}

templates/profile/modifier.html.twig
{% extends 'base.html.twig' %}
{% block title %}Modifier Profil
{% endblock %}
{% block body %}
<a href="{{ path('app_home_page') }}">Page d'accueil</a>
<a href="{{ path('profile_index') }}">Profil</a>
	<h1>Modifier Profil</h1>
	{{ form_errors(pictureProfil) }}
	{{ form_start(pictureProfil) }}
	{{ form_rest(pictureProfil.picture) }}
	<button type="submit">Valider</button>
	{{ form_end(pictureProfil) }}
{% endblock %}

templates/profile/posts.html.twig
{% extends 'base.html.twig' %}
{% block title %}Profil Utilisateur
{% endblock %}

{% block body %}
	<a href="{{ path('app_home_page') }}">Page d'accueil</a>
	<a href="{{ path('profile_index') }}">Profil</a>
	<div class="container text-center">
		<div>
			<div class="col" _msttexthash="77766" _msthash="252">

				<h1>Hello
					{{ app.user.username }}!</h1>
				{% if app.user.photo %}
					<img src="{{ asset('uploads/' ~ app.user.photo) }}" alt="Photo de profil">
				{% else %}
					<p>Aucune photo de profil.</p>
				{% endif %}
			</div>
		</div>
		<div class="row">
			<div>
				<p>écrire ici sa bio</p>
			</div>

			<div class="col" _msttexthash="52403" _msthash="256">
				<a href="{{ path('profile_modifier') }}" class="btn-primary">Modifier le profil</a>
			</div>
		</div>
	</div>
	<div class="col">
		<p>Posts</p>
	</div>
	{% for post in posts %}
		<div class="col">{{ post.author.username }}</div>
		<div class="col">{{ post.content }}</div>
		<div class="col">{{ post.createdAt|date('d/m/Y H:i') }}</div>

	{% endfor %}
{% endblock %}